[paths]
question_file = "/home/chenkai/VideoUnderstanding/datasets/videomme2/videovista2_no_answer.json"
video_base_dir = "/data/ck_data/VideoVista-2"
save_path = "/home/chenkai/VideoUnderstanding/output/result/raw_result/baseline-videovista2.json"
model_path = "/data/ck_data/models/Qwen-3VL-8B-instruct"

[runtime]
cuda_device = 0

[model]
trust_remote_code = true
tensor_parallel_size = 1
max_model_len = 256000
async_scheduling = true
max_pixels = 230400
num_frames = 180

[generation]
temperature = 0.0
top_p = 1.0
max_tokens = 32
repetition_penalty = 1.0

[prompt]
answer_instruction = "Answer the question only with single option's letter. For example: A"

[logging]
log_file = "../../scripts/log/test.log"
